target-version = "py310"
line-length = 110

[lint]
select = [
    "E",
    "W",
    "F",
    "I",
    "D",
    "PL",
    "NPY",
    "RUF",
    "UP",
    "S",
]
unfixable = [
    "PD002",
]
ignore = [
    "D100",
    "D105", # Missing docstring in magic method
    "D200",
    "D400",
    "UP007",
]

[lint.per-file-ignores]
"test*.py" = [
    "D",  # Documentation not needed in tests
    "S101",  # S101 Use of `assert` detected
    "PLR2004", # Magic value used in comparison
    "PLR0913" # Too many arguments in function definition
]
"conftest.py" = [
    "D",  # Documentation not needed in tests
    "S101",  # S101 Use of `assert` detected
    "PLR2004" # Magic value used in comparison
]
"docs/*" = [
    "D",
    "E402",  # Module level import not at top of file
    "S101",  # Use of `assert` detected
    "PLR2004",  # Magic value used in comparison.
]
"*/migrations/versions/*" = [
    "D103",  # Missing docstring in public function
]
"scripts/*" = [
    "S101" # S101 Use of `assert` detected
]
"stubs/*" = [
    "PLR0913",  # Too many arguments in function definition
]

[lint.isort]
known-first-party = ["cmip_ref", "cmip_ref_core"]

[lint.pydocstyle]
convention = "numpy"

[format]
docstring-code-format = true
