[project]
name = "climate-ref-celery"
version = "0.6.4"
description = "Celery app for mananging tasks and workers"
readme = "README.md"
authors = [
    { name = "Jared Lewis", email = "jared.lewis@climate-resource.com" }
]
license = "Apache-2.0"
requires-python = ">=3.11"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering",
    "License :: OSI Approved :: Apache Software License",
]
dependencies = [
    "climate-ref",
    "climate-ref-core",
    "celery[redis]>=5.4.0",
    "typer>=0.12.0",
    "environs>=11",
    "loguru>=0.7.2",
    "tqdm>=4.67.1",
]

[project.scripts]
ref-celery = "climate_ref_celery.cli:app"


[dependency-groups]
dev = [
    "celery-types>=0.23.0",
    "types-tqdm>=4.67.0.20250301",
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
