# Deploys the published wheels to PyPI
# Uses the artifact from the release job to publish to PyPI

name: Deploy

on:
  release:
    types: [published]

defaults:
  run:
    shell: bash

jobs:
  deploy-pypi:
    name: Deploy to PyPI
    # Having an environment for deployment is strongly recommend by PyPI
    # https://docs.pypi.org/trusted-publishers/adding-a-publisher/#github-actions
    environment: deploy
    runs-on: ubuntu-latest
    permissions:
      # this permission is mandatory for trusted publishing with PyPI
      id-token: write
    steps:
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'CMIP-REF/cmip-ref'
          version: tags/${{  github.ref_name }}
          regex: true
          file: ".*"
          target: 'dist/'
          token: ${{ secrets.PAT }}
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.x"
          python-version: "3.12"
      - name: Verify installable
        run: uv pip install dist/*.whl
      - name: Publish to PyPI
        run: |
          uv publish
